spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true   
  datasource: 
    url: jdbc:mysql://localhost:3306/lbs
    username: root
    password: root
    
    

application-properties:
  internal-system:
    environment-type: dev